# Generated by Django 3.2.4 on 2021-09-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ceo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('ceo', models.CharField(max_length=200)),
                ('since', models.IntegerField()),
            ],
        ),
    ]
